In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../01_python/data/sales.csv')

In [3]:
df

          date         product     category quantity  unit_price
0   2026-01-05          Laptop  Electronics        2      750.00
1   2026-01-07           Mouse  Electronics       10       15.50
2   2026-01-12      Desk Chair    Furniture        3      120.00
3   2026-02-02        Notebook   Stationery       50        2.25
4   2026-02-14         Monitor  Electronics        4      210.00
5   2026-02-20       Bookshelf    Furniture        1       95.00
6   2026-03-03        Pen Pack   Stationery       30        4.80
7   2026-03-09        Keyboard  Electronics        6       45.00
8   2026-03-15       Desk Lamp    Furniture     five       30.00
9   2026-03-21         Stapler          NaN        8        7.50
10  2026-04-01          Webcam  Electronics        5       60.00
11  2026-04-11  Filing Cabinet    Furniture        2      180.00

In [7]:
df["quantity"]

0        2
1       10
2        3
3       50
4        4
5        1
6       30
7        6
8     five
9        8
10       5
11       2
Name: quantity, dtype: str

In [11]:
df.head()

         date     product     category quantity  unit_price
0  2026-01-05      Laptop  Electronics        2      750.00
1  2026-01-07       Mouse  Electronics       10       15.50
2  2026-01-12  Desk Chair    Furniture        3      120.00
3  2026-02-02    Notebook   Stationery       50        2.25
4  2026-02-14     Monitor  Electronics        4      210.00

In [10]:
df.shape

(12, 5)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        12 non-null     str
 1   product     12 non-null     str
 2   category    11 non-null     str
 3   quantity    12 non-null     str
 4   unit_price  12 non-null     float64
dtypes: float64(1), str(4)
memory usage: 612.0 bytes

In [13]:
df.isna()

     date  product  category  quantity  unit_price
0   False    False     False     False       False
1   False    False     False     False       False
2   False    False     False     False       False
3   False    False     False     False       False
4   False    False     False     False       False
5   False    False     False     False       False
6   False    False     False     False       False
7   False    False     False     False       False
8   False    False     False     False       False
9   False    False      True     False       False
10  False    False     False     False       False
11  False    False     False     False       False

In [14]:
df.isna().sum()

date          0
product       0
category      1
quantity      0
unit_price    0
dtype: int64

In [16]:
df.isna()
df.isna().sum()

date          0
product       0
category      1
quantity      0
unit_price    0
dtype: int64

In [18]:
df.describe()

       unit_price
count   12.000000
mean   126.670833
std    208.180124
min      2.250000
25%     13.500000
50%     52.500000
75%    135.000000
max    750.000000

## Exercise 1 answers
1. **12 rows, 5 columns** (`df.shape` → `(12, 5)`).
2. `quantity` is `str` because row 8 (Desk Lamp) contains the text `"five"`.
   A column can only have one type, so pandas stored the whole column as text.
   Even `"2"` is text now, so you can't do maths with it until it's converted.
3. `category` has 1 missing value (row 9, Stapler). pandas put `NaN` there,
   its marker for a missing value (like `null` in PHP).